config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get '/tips', to: 'tips#index'
  get '/bloom_state', to: 'tips#bloom_state'
  get '/cloning', to: 'tips#cloning'
  get '/curing', to: 'tips#curing'
  get '/environment', to: 'tips#environment'
  get '/pruning', to: 'tips#pruning'
  get '/topping', to: 'tips#topping'
  get '/veg_state', to: 'tips#veg_state'
  get '/soil', to: 'tips#soil'
  get '/hydroponics', to: 'tips#hydroponics'
  get '/co2enrichment', to: 'tips#co2enrichment'
  get '/training', to: 'tips#training'

  resources :users

  resources :gardens do
    resources :crops
    resources :caretakers
  end

  resources :crops do
    resources :plants
  end

  resources :plants do
    resources :plant_entries
  end

  resources :plant do
    resources :general_notes
  end

  resources :plant do
    resources :sprayings
  end

  resources :plant do
    resources :plant_images
  end

  resources :plant do
    resources :stage_of_growths
  end

  resources :plant do
    resources :plant_tasks
  end

  resources :plant do
    resources :feedings
  end



  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-in', to: 'sessions#new'
  post 'sign-in', to: 'sessions#create'
  get 'sign-out', to: 'sessions#destroy'

end

app/models/feeding.rb
class Feeding < ActiveRecord::Base

  validates :water_amount || :nutrients_added, :presence => true

  has_many :plant_entries
  has_many :plants, through: :plant_entries
end

app/controllers/feedings_controller.rb
class FeedingsController < ApplicationController

  def index
    @feedings = Feedings.all
  end

  def new
    @feeding = Feeding.new
  end

  def create
    @feeding = Feeding.new(feeding_params)
    if @feeding.save
      flash[:notice] = 'Feeding successfully added'
      redirect_to plant_entry_feedings_path
    else
      render :new
    end
  end

  def edit
    @feeding = Feeding.find(params[:id])
  end

  def show
    @feeding = Feeding.find(params[:id])
  end

  def update
    @feeding = Feeding.find(params[:id])
    if @feeding.update(feeding_params)
      flash[:notice] = 'Feeding successfully updated!'
      redirect_to plant_entry_feedings_path
    else
      render :edit
    end
  end

  def destroy
    feeding = Feeding.find(params[:id])
    feeding.destroy
    flash[:error] = "Feeding was deleted"
    redirect_to plant_entry_feedings_path
  end

  private

  def feeding_params
    params.require(:feeding).permit(:water_amount, :nutrients_added, :ppm_level, :ph_level, :plant_entry_id)
  end

end

app/views/feedings/_form.html.haml
= form_for @feeding, html: {class: "form-horizontal"} do |f|
  = render partial: "/shared/errors", locals:{object: @feeding}
  .row
    .well.col-md-offset-2.col-md-8
      .form-group
        = f.label :water_amount, class: "col-md-4 control-label"
        .col-md-8
          = f.text_field :water_amount, class: "form-control"
      .form-group
        = f.label :nutrients_added, class: "col-md-4 control-label"
        .col-md-8
          = f.text_field :nutrients_added, class: "form-control"
      .form-group
        = f.label :ppm_level, class: "col-md-4 control-label"
        .col-md-8
          = f.text_field :ppm_level, class: "form-control"
      .form-group
        = f.label :ph_level, class: "col-md-4 control-label"
        .col-md-8
          = f.text_field :ph_level, class: "form-control"
      .form-group
        .col-md-offset-4.col-md-4
          = f.submit class: "btn btn-success form-control"

app/views/feedings/edit.html.haml
.page-header
  = link_to "Delete Feeding", plant_entry_feeding_path, method: :delete, class: "btn btn-danger pull-right", data: {confirm: 'Are you sure man?!'}
  %h2 Edit Feeding

%ol.breadcrumb
  %li=link_to "Garden", gardens_path
  %li=link_to ""

= render "form"

app/views/feedings/index.html.haml
.page-header
  = link_to "New Feed", new_plant_entry_feeding_path, class: "btn btn-success pull-right"
  %h2 List of Plant Feedings

%table.table.striped
  %thead
    %tr
      %th Water Amount
      %th Nutrients Added
      %th PPM Level
      %th PH level

  %tbody
    - @feedings.each do |feeding|
      %tr
        %td= link_to feeding.water_amount, plant_entry_feeding_path(@plant_entry, feeding)
        %td= feeding.nutrients_added
        %td= feeding.ppm_level
        %td= feeding.ph_level

app/views/feedings/new.html.haml
.page-header
  %h2 New Feeding

= render "form"

app/views/feedings/show.html.haml
.page-header
  .pull-right
    =link_to "Edit", edit_plant_entry_feeding_path(@plant_entry, @feeding), class: "btn btn-info"
  %h2 Feeding

%dl.dl-horizontal
  %dt Plant ID #
  %dd= @feeding.plant_id
  %dt Water Amount
  %dd= @feeding.water_amount
  %dt Nutrients Added
  %dd= @feeding.nutrients_added
  %dt PPM Level
  %dd= @feeding.ppm_level
  %dt Ph Level
  %dd= @feeding.ph_level
  %dt Last Feeding
  %dd= @feeding.created_at.strftime("%a, %B %d, %Y, at %l:%M %p")