config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get '/tips', to: 'tips#index'
  get '/bloom_state', to: 'tips#bloom_state'
  get '/cloning', to: 'tips#cloning'
  get '/curing', to: 'tips#curing'
  get '/environment', to: 'tips#environment'
  get '/pruning', to: 'tips#pruning'
  get '/topping', to: 'tips#topping'
  get '/veg_state', to: 'tips#veg_state'
  get '/soil', to: 'tips#soil'
  get '/hydroponics', to: 'tips#hydroponics'
  get '/co2enrichment', to: 'tips#co2enrichment'
  get '/training', to: 'tips#training'

  resources :users

  resources :gardens do
    resources :crops
    resources :caretakers
  end

  resources :crops do
    resources :plants
  end

  resources :plants do
    resources :plant_entries
  end

  resources :plant do
    resources :general_notes
  end

  resources :plant do
    resources :sprayings
  end

  resources :plant do
    resources :plant_images
  end

  resources :plant do
    resources :stage_of_growths
  end

  resources :plant do
    resources :plant_tasks
  end

  resources :plant do
    resources :feedings
  end



  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-in', to: 'sessions#new'
  post 'sign-in', to: 'sessions#create'
  get 'sign-out', to: 'sessions#destroy'

end

app/models/plant.rb
class Plant < ActiveRecord::Base
  attr_accessor :plant_picture
  validates :strain_name, :presence => true

  belongs_to :crop

  has_many :plant_entries, dependent: :destroy
  has_many :feedings, through: :plant_entries
  has_many :general_notes, through: :plant_entries
  has_many :plant_images, through: :plant_entries
  has_many :plant_tasks, through: :plant_entries
  has_many :sprayings, through: :plant_entries
  has_many :stage_of_growths, through: :plant_entries

  accepts_nested_attributes_for :plant_tasks, :allow_destroy => true
  accepts_nested_attributes_for :general_notes, :allow_destroy => true
  accepts_nested_attributes_for :stage_of_growths, :allow_destroy => true
  accepts_nested_attributes_for :feedings, :allow_destroy => true
  accepts_nested_attributes_for :plant_images, :allow_destroy => true
  accepts_nested_attributes_for :sprayings, :allow_destroy => true

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  before_action :find_and_set_plant

  def index
    @plants = @crop.plants.all
  end

  def new
    @plant = @crop.plants.new
  end

  def create
    @plant = @crop.plants.new(plant_params)
    if @plant.save
      flash[:notice] = 'Plant successfully created'
      redirect_to crop_plants_path
    else
      render :new
    end
  end

  def edit
    @plant = @crop.plants.find(params[:id])
  end

  def show
    @plant = @crop.plants.find(params[:id])
  end

  def update
    @plant = @crop.plants.find(params[:id])
    if @plant.update(plant_params)
      flash[:notice] = 'Plant Successfully updated!'
      redirect_to crop_plants_path
    else
      render :edit
    end
  end

  def destroy
    plant = @crop.plants.find(params[:id])
    plant.destroy
    flash[:error] = "Plant was deleted"
    redirect_to crop_plants_path
  end

  private

  def plant_params
    params.require(:plant).permit(:strain_name, :sex, :from, :crop_id, :id_number)
  end

  def find_and_set_plant
    @crop = Crop.find(params[:crop_id])
  end

  end

app/views/plants/_form.html.haml
= form_for [@crop, @plant], html: {class: "form-horizontal"} do |f|
  = render partial: "/shared/errors", locals:{object: @plant}
  .row
    .well.col-md-offset-2.col-md-8
      .form-group
        = f.label :strain_name, class: "col-md-4 control-label"
        .col-md-8
          = f.text_field :strain_name, class: "form-control"
      .form-group
        = f.label :sex, class: "col-md-4 control-label"
        .col-md-8
          = f.text_field :sex, class: "form-control"
      .form-group
        = f.label :from, class: "col-md-4 control-label"
        .col-md-8
          = f.text_field :from, class: "form-control"
      .form-group
        = f.label :id_number, class: "col-md-4 control-label"
        .col-md-8
          = f.text_field :id_number, class: "form-control"
      .form-group
        .col-md-offset-4.col-md-4
          = f.submit class: "btn btn-success form-control"

app/views/plants/edit.html.haml
.page-header
  = link_to "Delete Plant", crop_plant_path, method: :delete, class: "btn btn-danger pull-right", data: {confirm: 'Are you sure man?!'}
  %h2 Edit Plant

%ol.breadcrumb
  %li=link_to "Home", root_path
  %li=link_to "Garden", gardens_path
  -# %li=link_to "Crops", garden_crops_path(@garden)
  %li=link_to "Plants", crop_plants_path(@crop)
  %li.active Edit Plant

= render "form"

app/views/plants/index.html.haml
.page-header
  = link_to "New Plant", new_crop_plant_path(@crop), class: "btn btn-success pull-right"
  %h2 List of Plants

%ol.breadcrumb
  %li=link_to "Home", root_path
  %li=link_to "Garden", gardens_path
  -# %li=link_to "Crops", garden_crops_path(@garden)
  %li.active Plants

%table.table.striped
  %thead
    %tr
      %th.text-center.col-md-1 ID #
      %th.text-center.col-md-2 Strain Name
      %th.text-center.col-md-1 Sex
      %th.text-center.col-md-1 From
      %th.text-center.col-md-1{:colspan => 2} Entries

      -# %th.text-center.col-md-1{:colspan => 2} Plant Tasks
      -# %th.text-center.col-md-1{:colspan => 2} Stage Of Growth
      -# %th.text-center.col-md-1{:colspan => 2} Notes
      -# %th.text-center.col-md-1{:colspan => 2} Pictures


  %tbody
    - @plants.each do |plant|
      %tr
        %td.text-center.col-md-1= plant.id_number
        %td.text-center.col-md-2= link_to plant.strain_name, crop_plant_path(@crop, plant)
        %td.text-center.col-md-1= plant.sex
        %td.text-center.col-md-1= plant.from
        %td.text-center.col-md-.5= link_to "", plant_plant_entries_path(plant), class: "glyphicon glyphicon-home"
        %td.text-center.col-md-.5= link_to "", new_plant_plant_entry_path(plant), class: "glyphicon glyphicon-plus"

        -# %td.text-center.col-md-.5= link_to "", plant_plant_tasks_path(plant), class: "glyphicon glyphicon-home"
        -# %td.text-center.col-md-.5= link_to "", new_plant_plant_task_path(plant), class: "glyphicon glyphicon-plus"
        -# %td.text-center.col-md-.5= link_to "", plant_stage_of_growths_path(plant), class: "glyphicon glyphicon-home"
        -# %td.text-center.col-md-.5= link_to "", new_plant_stage_of_growth_path(plant), class: "glyphicon glyphicon-plus"
        -# %td.text-center.col-md-.5= link_to "", plant_general_notes_path(plant), class: "glyphicon glyphicon-home"
        -# %td.text-center.col-md-.5= link_to "", new_plant_general_note_path(plant), class: "glyphicon glyphicon-plus"
        -# %td.text-center.col-md-.5= link_to "", plant_plant_images_path(plant), class: "glyphicon glyphicon-camera"
        -# %td.text-center.col-md-.5= link_to "", new_plant_plant_image_path(plant), class: "glyphicon glyphicon-plus"

app/views/plants/new.html.haml
.page-header
  %h2 New Plant

%ol.breadcrumb
  %li=link_to "Home", root_path
  %li=link_to "Garden", gardens_path
  -# %li=link_to "Crops", garden_crops_path(@garden)
  %li=link_to "Plants", crop_plants_path(@crop)
  %li.active New Plant

= render "form"

app/views/plants/show.html.haml
.page-header
  .pull-right
    =link_to "Edit", edit_crop_plant_path(@crop, @plant), class: "btn btn-info"
  %h2
    =@plant.strain_name
%ol.breadcrumb
  %li=link_to "Home", root_path
  %li=link_to "Garden", gardens_path
  -# %li=link_to "Crops", garden_crops_path(@garden)
  %li=link_to "Plants", crop_plants_path(@crop)
  %li.active= @plant.strain_name

%dl.dl-horizontal
  %dt Sex
  %dd= @plant.sex
  %dt From
  %dd= @plant.from
  %dt Stage Of Growth
  %dd=link_to "Record Plant Tasks", plant_entry_plant_tasks_path(@plant), class: "btn btn-success"

-# = link_to "copy", copy_crop_plant_path(params[:id])