config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get '/tips', to: 'tips#index'
  get '/bloom_state', to: 'tips#bloom_state'
  get '/cloning', to: 'tips#cloning'
  get '/curing', to: 'tips#curing'
  get '/environment', to: 'tips#environment'
  get '/pruning', to: 'tips#pruning'
  get '/topping', to: 'tips#topping'
  get '/veg_state', to: 'tips#veg_state'
  get '/soil', to: 'tips#soil'
  get '/hydroponics', to: 'tips#hydroponics'
  get '/co2enrichment', to: 'tips#co2enrichment'
  get '/training', to: 'tips#training'

  resources :users

  resources :gardens do
    resources :crops
    resources :caretakers
  end

  resources :crops do
    resources :plants
  end

  resources :plants do
    resources :plant_entries
  end

  resources :plant do
    resources :general_notes
  end

  resources :plant do
    resources :sprayings
  end

  resources :plant do
    resources :plant_images
  end

  resources :plant do
    resources :stage_of_growths
  end

  resources :plant do
    resources :plant_tasks
  end

  resources :plant do
    resources :feedings
  end



  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-in', to: 'sessions#new'
  post 'sign-in', to: 'sessions#create'
  get 'sign-out', to: 'sessions#destroy'

end

app/models/crop.rb
class Crop < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :garden
  has_many :plants, dependent: :destroy

end

app/controllers/crops_controller.rb
class CropsController < ApplicationController

  before_action :find_and_set_crop

  def index
    @crops = @garden.crops.all
  end

  def new
    @crop = @garden.crops.new
  end

  def create
    @crop = @garden.crops.new(crop_params)
    if @crop.save
      flash[:notice] = 'Crop successfully created'
      redirect_to garden_crops_path
    else
      render :new
    end
  end

  def edit
    @crop = @garden.crops.find(params[:id])
  end

  def show
    @crop = @garden.crops.find(params[:id])
  end

  def update
    @crop = @garden.crops.find(params[:id])
    if @crop.update(crop_params)
      flash[:notice] = 'Crop Successfully updated!'
      redirect_to garden_crops_path
    else
      render :edit
    end
  end

  def destroy
    crop = @garden.crops.find(params[:id])
    crop.destroy
    flash[:error] = "Crop was deleted"
    redirect_to garden_crops_path
  end

  private

  def crop_params
    params.require(:crop).permit(:name, :garden_id)
  end

  def find_and_set_crop
    @garden = Garden.find(params[:garden_id])
  end

end

app/views/crops/_form.html.haml
= form_for [@garden, @crop], html: {class: "form-horizontal"} do |f|
  = render partial: "/shared/errors", locals:{object: @crop}
  .row
    .well.col-md-offset-2.col-md-8
      .form-group
        = f.label :name, class: "col-md-4 control-label"
        .col-md-8
          = f.text_field :name, class: "form-control"
      .form-group
        .col-md-offset-4.col-md-4
          = f.submit class: "btn btn-success form-control"

app/views/crops/edit.html.haml
.page-header
  = link_to "Delete Crop", garden_crop_path, method: :delete, class: "btn btn-danger pull-right", data: {confirm: 'Are you sure man?!'}
  %h2 Edit Crop

%ol.breadcrumb
  %li=link_to "Home", root_path
  %li=link_to "Garden", gardens_path
  %li=link_to "Crops", garden_crops_path(@garden)
  %li.active Edit Crop

= render "form"

app/views/crops/index.html.haml
.page-header
  %h2 List of Crops

%ol.breadcrumb
  %li=link_to "Home", root_path
  %li=link_to "Garden", gardens_path
  %li.active Crops

- @crops.each do |crop|

  = link_to crop.name, garden_crop_path(@garden, crop)
  %hr

app/views/crops/new.html.haml
.page-header
  %h2 New Crop

%ol.breadcrumb
  %li=link_to "Home", root_path
  %li=link_to "Garden", gardens_path
  %li=link_to "Crops", garden_crops_path(@garden)
  %li.active New Crop

= render "form"

app/views/crops/show.html.haml
.page-header
  .pull-right
    = link_to 'Edit Crop', edit_garden_crop_path(@garden, @crop), class: "btn btn-success"
  %h2= @crop.name

%ol.breadcrumb
  %li=link_to "Home", root_path
  %li=link_to "Garden", gardens_path
  %li=link_to "Crops", garden_crops_path(@garden)
  %li.active= @crop.name

= link_to 'List of Plants', crop_plants_path(@crop)