config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get '/tips', to: 'tips#index'
  get '/bloom_state', to: 'tips#bloom_state'
  get '/cloning', to: 'tips#cloning'
  get '/curing', to: 'tips#curing'
  get '/environment', to: 'tips#environment'
  get '/pruning', to: 'tips#pruning'
  get '/topping', to: 'tips#topping'
  get '/veg_state', to: 'tips#veg_state'
  get '/soil', to: 'tips#soil'
  get '/hydroponics', to: 'tips#hydroponics'
  get '/co2enrichment', to: 'tips#co2enrichment'
  get '/training', to: 'tips#training'

  resources :users

  resources :gardens do
    resources :crops
    resources :caretakers
  end

  resources :crops do
    resources :plants
  end

  resources :plants do
    resources :plant_entries
  end

  resources :plant do
    resources :general_notes
  end

  resources :plant do
    resources :sprayings
  end

  resources :plant do
    resources :plant_images
  end

  resources :plant do
    resources :stage_of_growths
  end

  resources :plant do
    resources :plant_tasks
  end

  resources :plant do
    resources :feedings
  end



  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-in', to: 'sessions#new'
  post 'sign-in', to: 'sessions#create'
  get 'sign-out', to: 'sessions#destroy'

end

app/models/plant_entry.rb
class PlantEntry < ActiveRecord::Base

  belongs_to :plant
  belongs_to :plant_task, polymorphic: true
  belongs_to :feedings
  belongs_to :general_notes
  belongs_to :stage_of_growths
  belongs_to :plant_images
  belongs_to :sprayings

end

app/controllers/plant_entries_controller.rb
class PlantEntriesController < ApplicationController

  before_action :find_and_set_plant_entry

  def index
    @plant_entries = @plant.plant_entries.all
  end

  def new
    @plant_entry = @plant.plant_entries.new
    GeneralNote.new(plant_entry_id: @plant_entry.id)
    # @plant_entry.feedings.build
    # @plant_entry.plant_tasks.build
    # @plant_entry.stage_of_growths.build
    # @plant_entry.plant_images.build
    # @plant_entry.sprayings.build
    # @plant_entry.general_notes.build
  end

  def create
    @plant_entry = @plant.plant_entries.new(plant_entry_params)
    if @plant_entry.save
      flash[:notice] = 'Plant entry were successfully added'
      redirect_to plant_plant_entries_path
    else
      render :new
    end
  end

  def edit
    @plant_entry = @plant.plant_entries.find(params[:id])
  end

  def show
    @plant_entry = @plant.plant_entries.find(params[:id])
  end

  def update
    @plant_entry = @plant.plant_entries.find(params[:id])
    if @plant_entry.update(plant_entry_params)
      flash[:notice] = 'Plant entry were successfully updated!'
      redirect_to plant_plant_entries_path
    else
      render :edit
    end
  end

  def destroy
    plant_entry = @plant.plant_entries.find(params[:id])
    plant_entry.destroy
    flash[:error] = "Plant entry was deleted"
    redirect_to plant_plant_entries_path
  end

  private

  def plant_entry_params
    params.require(:plant_entry).permit(:entry_datetime, :plant_id, general_notes: [:id, :notes, :plant_entry_id])
  end

  def find_and_set_plant_entry
    @plant = Plant.find(params[:plant_id])
  end

end

app/views/plant_entries/_form.html.haml
= form_for [@plant, @plant_entry], html: {class: "form-horizontal", multipart: true} do |e|
  = render partial: "/shared/errors", locals:{object: @plant_entry}
  .form-group
    = e.label :entry_datetime, "Entry Date", class: "col-md-4 control-label"
    .col-md-3
      = e.date_field :entry_datetime, class: "form-control"
  %table.col-md-12
    %tr
      %td
        %center
          %h3 Feedings
          .well.col-md-offset-2.col-md-8
            = e.fields_for :feeding do |f|
              .form-group
                = f.label :water_amount, class: "col-md-4 control-label"
                .col-md-8
                  = f.text_field :water_amount, class: "form-control"
              .form-group
                = f.label :nutrients_added, class: "col-md-4 control-label"
                .col-md-8
                  = f.text_field :nutrients_added, class: "form-control"
              .form-group
                = f.label :ppm_level, class: "col-md-4 control-label"
                .col-md-8
                  = f.text_field :ppm_level, class: "form-control"
              .form-group
                = f.label :ph_level, class: "col-md-4 control-label"
                .col-md-8
                  = f.text_field :ph_level, class: "form-control"

      %td
        %center
          %h3 Tasks
          .well.col-md-offset-2.col-md-8
            = e.fields_for :plant_task do |t|
              %br
              .form-group
                = t.label :topped, class: "col-md-4 control-label"
                .col-md-8
                  = t.check_box :topped, class: "form-control"
              .form-group
                = t.label :trimmed, class: "col-md-4 control-label"
                .col-md-8
                  = t.check_box :trimmed, class: "form-control"
              .form-group
                = t.label :staked, class: "col-md-4 control-label"
                .col-md-8
                  = t.check_box :staked, class: "form-control"
              .form-group
                = t.label :clipped, class: "col-md-4 control-label"
                .col-md-8
                  = t.check_box :clipped, class: "form-control"

    %tr
      %td
        %center
          %h3 Spray
          .well.col-md-offset-2.col-md-8
            = e.fields_for :spraying do |s|
              %br
              %br
              .form-group
                = s.label :water_amount, class: "col-md-4 control-label"
                .col-md-8
                  = s.text_field :water_amount, class: "form-control"
              %br
              %br
              .form-group
                = s.label :chemicals_added, class: "col-md-4 control-label"
                .col-md-8
                  = s.text_field :chemicals_added, class: "form-control"
              %br
              %br

      %td
        %center
          %h3 Stage Of Growth
          .well.col-md-offset-2.col-md-8
            = e.fields_for :stage_of_growth do |g|
              .form-group
                = g.label :stage, class: "col-md-4 control-label"
                .col-md-8
                  = g.text_field :stage, class: "form-control"
              .form-group
                = g.label :plant_date, class: "col-md-4 control-label"
                .col-md-8
                  = g.date_field :plant_date, class: "form-control"
              .form-group
                = g.label :pot_size, class: "col-md-4 control-label"
                .col-md-8
                  = g.text_field :pot_size, class: "form-control"
              .form-group
                = g.label :grow_medium, class: "col-md-4 control-label"
                .col-md-8
                  = g.text_field :grow_medium, class: "form-control"
              .form-group
                = g.label :nutrients_added, class: "col-md-4 control-label"
                .col-md-8
                  = g.text_field :nutrients_added, class: "form-control"

    %tr
      %td
        %center
          %h3 Notes
          .well.col-md-offset-2.col-md-8
            = e.fields_for :general_note do |n|
              .form-group
                = n.label :notes, class: "col-md-4 control-label"
                .col-md-8
                  = n.text_area :notes, class: "form-control"

      %td
        %center
          %h3 Picture
          .well.col-md-offset-2.col-md-8
            = e.fields_for :plant_image do |i|
              %br
              .form-group
                = i.label :plant_picture, class: "col-md-4 control-label"
                .col-md-8
                  = i.file_field :plant_picture, class: "form-control"

  .form-group
    .col-md-offset-4.col-md-4
      = e.submit class: "btn btn-success form-control"

app/views/plant_entries/edit.html.haml
.page-header
  = link_to "Delete Plant Entry", plant_plant_entry_path, method: :delete, class: "btn btn-danger pull-right", data: {confirm: 'Are you sure man?!'}
  %h2 Edit Plant Entry

= render "form"

app/views/plant_entries/index.html.haml
.page-header
  = link_to "New Plant Entry", new_plant_plant_entry_path(@plant), class: "btn btn-success pull-right"
  %h2 List of Plants Entries

%ol.breadcrumb
  %li=link_to "Home", root_path
  %li=link_to "Garden", gardens_path
  -# %li=link_to "Crops", garden_crops_path(@garden)
  -# %li=link_to "Plant", crop_plants_path(@crop)
  %li.active Plant Entries

%table.table.striped
  %thead
    %tr
      %th.text-center.col-md-1{:colspan => 2} Feedings
      %th
      %th.text-center.col-md-1{:colspan => 2} Sprayings
      %th
      %th.text-center.col-md-1{:colspan => 2} Plant Tasks
      %th
      %th.text-center.col-md-1{:colspan => 2} Stage Of Growth
      %th
      %th.text-center.col-md-1{:colspan => 2} Notes
      %th
      %th.text-center.col-md-1{:colspan => 2} Pictures

  %tbody
    %tr
      %td.text-center.col-md-.5= link_to "", plant_feedings_path(@plant), class: "glyphicon glyphicon-home"
      %td.text-center.col-md-.5= link_to "", new_plant_feeding_path(@plant), class: "glyphicon glyphicon-plus"
      %td
      %td.text-center.col-md-.5= link_to "", plant_sprayings_path(@plant), class: "glyphicon glyphicon-home"
      %td.text-center.col-md-.5= link_to "", new_plant_spraying_path(@plant), class: "glyphicon glyphicon-plus"
      %td
      %td.text-center.col-md-.5= link_to "", plant_plant_tasks_path(@plant), class: "glyphicon glyphicon-home"
      %td.text-center.col-md-.5= link_to "", new_plant_plant_task_path(@plant), class: "glyphicon glyphicon-plus"
      %td
      %td.text-center.col-md-.5= link_to "", plant_stage_of_growths_path(@plant), class: "glyphicon glyphicon-home"
      %td.text-center.col-md-.5= link_to "", new_plant_stage_of_growth_path(@plant), class: "glyphicon glyphicon-plus"
      %td
      %td.text-center.col-md-.5= link_to "", plant_general_notes_path(@plant), class: "glyphicon glyphicon-home"
      %td.text-center.col-md-.5= link_to "", new_plant_general_note_path(@plant), class: "glyphicon glyphicon-plus"
      %td
      %td.text-center.col-md-.5= link_to "", plant_plant_images_path(@plant), class: "glyphicon glyphicon-camera"
      %td.text-center.col-md-.5= link_to "", new_plant_plant_image_path(@plant), class: "glyphicon glyphicon-plus"

app/views/plant_entries/new.html.haml
.page-header
  %h2 New Plant Entry

= render "form"